#! /bin/bash
sudo docker stop testscript
sudo docker remove testscript
sudo docker pull thornburyjac/sp2024-ceg3120-proj:latest
sudo docker run -d -p 8080:80 --name testscript --restart always thornburyjac/sp2024-ceg3120-proj:latest
